name: build docs

on:
  push:
    branches: [ main ]

env:
  PNPM_VERSION: 8.4.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - run: pnpm install --frozen-lockfile
      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: jasonraimondi/ts-oauth2-server
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: npm install -g pnpm && pnpm install --frozen-lockfile && pnpm docs:build
          BUILD_DIR: docs/.vuepress/dist/
